use_frameworks!

platform :ios, '9.0'

target 'hello-cocoapod_Example' do
  pod 'hello-cocoapod', :path => '../'

  target 'hello-cocoapod_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble'
  end
end
